In [18]:
import pandas as pd
import numpy as np

project_path = r"C:\Users\Bawan Singh\OneDrive\Documents\Arshleen\market-portfolio-risk-analysis"

In [19]:
import pandas as pd
import numpy as np

project_path = r"C:\Users\Bawan Singh\OneDrive\Documents\Arshleen\market-portfolio-risk-analysis"

returns = pd.read_csv(
    project_path + r"\data\processed\daily_returns.csv",
    index_col=0,
    parse_dates=True
)

portfolio_returns = pd.read_csv(
    project_path + r"\data\processed\portfolio_returns.csv",
    index_col=0,
    parse_dates=True
)

In [21]:
portfolio_annualized_return = pd.read_csv(
    project_path + r"\data\processed\portfolio_annualized_return.csv",
    index_col=0
).squeeze()

In [20]:
portfolio_annualized_volatility = pd.read_csv(
    project_path + r"\data\processed\portfolio_annualized_volatility.csv",
    index_col=0
).squeeze()

In [22]:
sharpe_ratio = pd.read_csv(
    project_path + r"\data\processed\sharpe_ratio.csv",
    index_col=0
).squeeze()

In [3]:
benchmark_returns=returns["SPY"]

In [24]:
portfolio_beta = {}

for portfolio in portfolio_returns.columns:
    covariance = portfolio_returns[portfolio].cov(benchmark_returns)
    benchmark_variance = benchmark_returns.var()
    
    portfolio_beta[portfolio] = covariance / benchmark_variance

portfolio_beta

{'Conservative': 0.36907091745125964,
 'Balanced': 0.5726078226503768,
 'Growth': 0.9617291402468516}

In [25]:
portfolio_beta_table = pd.Series(portfolio_beta)

portfolio_beta_table

Conservative    0.369071
Balanced        0.572608
Growth          0.961729
dtype: float64

In [6]:
treynor_ratio = portfolio_annualized_return / portfolio_beta_table

treynor_ratio

Conservative    0.284624
Balanced        0.215221
Growth          0.194737
dtype: float64

In [7]:
portfolio_beta_table

Conservative    0.369071
Balanced        0.572608
Growth          0.961729
dtype: float64

In [8]:
portfolio_annualized_return

Conservative    0.105047
Balanced        0.123237
Growth          0.187285
Name: 0, dtype: float64

In [9]:
treynor_ratio_table=pd.DataFrame({ "Treynor Ratio":treynor_ratio})
treynor_ratio_table.style.format("{:.2f}")

In [10]:
benchmark_annualized_return = benchmark_returns.mean() * 252

benchmark_annualized_return

0.17851768141943838

In [11]:
jensens_alpha = (
    portfolio_annualized_return
    - (portfolio_beta_table * benchmark_annualized_return)
)

jensens_alpha

Conservative    0.039161
Balanced        0.021016
Growth          0.015599
dtype: float64

In [12]:
jensens_alpha_table = pd.DataFrame({
    "Jensen's Alpha": jensens_alpha
})

jensens_alpha_table.style.format("{:.2%}")

In [13]:
jensens_alpha.to_csv(
    project_path + r"\data\processed\jensens_alpha.csv"
)

In [16]:
sharpe_ratio = pd.read_csv(
    project_path + r"\data\processed\sharpe_ratio.csv",
    index_col=0
).squeeze()

In [26]:
performance_summary = pd.DataFrame(
    index=portfolio_returns.columns
)

performance_summary["Annualized Return"] = portfolio_annualized_return
performance_summary["Annualized Volatility"] = portfolio_annualized_volatility
performance_summary["Sharpe Ratio"] = sharpe_ratio

In [27]:
performance_summary

              Annualized Return  Annualized Volatility  Sharpe Ratio
Conservative           0.105047               0.108104      0.971717
Balanced               0.123237               0.126049      0.977689
Growth                 0.187285               0.195982      0.955622

In [28]:
performance_summary["Beta"] = portfolio_beta_table
performance_summary

              Annualized Return  Annualized Volatility  Sharpe Ratio      Beta
Conservative           0.105047               0.108104      0.971717  0.369071
Balanced               0.123237               0.126049      0.977689  0.572608
Growth                 0.187285               0.195982      0.955622  0.961729

In [29]:
treynor_ratio = (
    portfolio_annualized_return
    / portfolio_beta_table
)

In [30]:
treynor_ratio

Conservative    0.284624
Balanced        0.215221
Growth          0.194737
dtype: float64

In [32]:
performance_summary["Treynor Ratio"] = treynor_ratio
performance_summary

,Annualized Return,Annualized Volatility,Sharpe Ratio,Beta,Treynor Ratio
Conservative,0.105047,0.108104,0.971717,0.369071,0.284624
Balanced,0.123237,0.126049,0.977689,0.572608,0.215221
Growth,0.187285,0.195982,0.955622,0.961729,0.194737

In [33]:
benchmark_annualized_return = benchmark_returns.mean() * 252

In [34]:
benchmark_annualized_return

0.17851768141943838

In [35]:
jensens_alpha = (
    portfolio_annualized_return
    - (portfolio_beta_table * benchmark_annualized_return)
)

In [36]:
jensens_alpha

Conservative    0.039161
Balanced        0.021016
Growth          0.015599
dtype: float64

In [37]:
performance_summary["Jensen's Alpha"] = jensens_alpha

In [38]:
performance_summary

,Annualized Return,Annualized Volatility,Sharpe Ratio,Beta,Treynor Ratio,Jensen's Alpha
Conservative,0.105047,0.108104,0.971717,0.369071,0.284624,0.039161
Balanced,0.123237,0.126049,0.977689,0.572608,0.215221,0.021016
Growth,0.187285,0.195982,0.955622,0.961729,0.194737,0.015599

In [39]:
performance_summary.to_csv(
    project_path + r"\data\processed\performance_summary.csv"
)